In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,45,43,54])

In [3]:
arr1

array([ 1,  2,  3, 45, 43, 54])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
len(arr1)

6

In [7]:
arr1[3]

45

In [9]:
arr1[-1]

54

In [11]:
arr2 = np.array([[1,2,3],[1,2,3]])

In [13]:
arr2

array([[1, 2, 3],
       [1, 2, 3]])

In [22]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]],[[1,2,3],[2,3,4]]])

In [23]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [18]:
arr3.size

12

In [19]:
arr2.size

6

In [24]:
arr3.shape

(3, 2, 3)

In [25]:
arr3.ndim

3

In [28]:
np.random.seed(10)
np.random.randint(0,10,15)

array([9, 4, 0, 1, 9, 0, 1, 8, 9, 0, 8, 6, 4, 3, 0])

In [33]:
np.random.seed(15)
np.random.randint(10,100,(3,2,5))

array([[[82, 22, 15, 10, 38],
        [37, 81, 85, 95, 57]],

       [[27, 41, 33, 42, 72],
        [20, 25, 78, 49, 47]],

       [[29, 54, 87, 70, 39],
        [89, 25, 66, 59, 11]]])

In [34]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [40]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [41]:
a1 = np.random.randint(1,20,15)

In [42]:
a1

array([ 1,  3, 12, 19,  2,  9,  7, 10,  3,  9,  9, 16,  4,  5,  8])

In [43]:
np.sum(a1)

117

In [44]:
np.max(a1)

19

In [45]:
np.min(a1)

1

In [46]:
np.mean(a1)

7.8

In [47]:
np.median(a1)

8.0

In [48]:
np.sort(a1)

array([ 1,  2,  3,  3,  4,  5,  7,  8,  9,  9,  9, 10, 12, 16, 19])

In [49]:
np.var(a1)

24.56

In [50]:
a2 = np.array([3,4,5,6])
a3 = np.array([4,5,6,7])

In [54]:
np.add(a2,a3)

array([ 7,  9, 11, 13])

In [52]:
np.multiply(a2,a3)

array([12, 20, 30, 42])

In [69]:
np.divide(a2,a2)

array([1., 1., 1., 1.])

In [70]:
np.flip(a2)

array([6, 5, 4, 3])